SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(S.TOTAL_SALES * B.PRICE) AS TOTAL_SALES
FROM BOOK B, AUTHOR A,
     (
     SELECT BOOK_ID, SUM(SALES) AS TOTAL_SALES
     FROM BOOK_SALES
     WHERE TO_CHAR(SALES_DATE, 'YYYY-MM') LIKE '2022-01'
     GROUP BY BOOK_ID
     ) S
WHERE B.BOOK_ID = S.BOOK_ID
      AND B.AUTHOR_ID = A.AUTHOR_ID
GROUP BY B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC;