SELECT *
FROM
    (
    SELECT I.ANIMAL_ID, I.NAME
    FROM ANIMAL_INS I INNER JOIN ANIMAL_OUTS O
         ON I.ANIMAL_ID = O.ANIMAL_ID
    ORDER BY (O.DATETIME - I.DATETIME) DESC
    )
WHERE ROWNUM <= 2;
