SELECT TO_CHAR(O.SALES_DATE, 'YYYY') AS YEAR,
       TO_NUMBER(TO_CHAR(O.SALES_DATE, 'MM')) AS MONTH,
       U.GENDER,
       COUNT(DISTINCT O.USER_ID) AS USERS
FROM USER_INFO U, ONLINE_SALE O
WHERE U.USER_ID = O.USER_ID
      AND U.GENDER IS NOT NULL
GROUP BY TO_CHAR(O.SALES_DATE, 'YYYY'), TO_CHAR(O.SALES_DATE, 'MM'), U.GENDER
ORDER BY YEAR, MONTH, GENDER