SELECT P.PRODUCT_ID, P.PRODUCT_NAME, P.PRICE * O.TOTAL_AMOUNT AS TOTAL_SALES
FROM FOOD_PRODUCT P,
    (
    -- 생산일자가 2022년 5월인 식품들의 식품 ID와 총주문량
    SELECT DISTINCT PRODUCT_ID, SUM(AMOUNT) AS TOTAL_AMOUNT
    FROM FOOD_ORDER
    WHERE TO_CHAR(PRODUCE_DATE, 'YYYY-MM') LIKE '2022-05'
    GROUP BY PRODUCT_ID
    ) O
WHERE P.PRODUCT_ID = O.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC;