SELECT FLAVOR
FROM
    (
    SELECT F.FLAVOR, F.TOTAL_ORDER + J.TOTAL_ORDER AS TOTAL_ORDER
    FROM
        (
        SELECT FLAVOR, TOTAL_ORDER
        FROM FIRST_HALF
        ) F
        FULL OUTER JOIN
        (
        SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
        FROM JULY 
        GROUP BY FLAVOR
        ) J
        ON F.FLAVOR = J.FLAVOR
    ORDER BY TOTAL_ORDER DESC
    )
WHERE ROWNUM <= 3;