SELECT A.APNT_NO, P.PT_NAME, A.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM PATIENT P, DOCTOR D,
     (
     SELECT APNT_NO, PT_NO, MCDP_CD, MDDR_ID, APNT_YMD
     FROM APPOINTMENT
     WHERE TO_CHAR(APNT_YMD, 'YYYY-MM-DD') LIKE '2022-04-13'
     AND MCDP_CD LIKE 'CS'
     AND APNT_CNCL_YN LIKE 'N'
     ) A
WHERE A.PT_NO = P.PT_NO
      AND A.MDDR_ID = D.DR_ID
ORDER BY A.APNT_YMD ASC;