SELECT TO_NUMBER(TO_CHAR(H.START_DATE, 'MM')) AS MONTH, H.CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H,
     (
     -- 2022년 8월부터 2022년 10월까지 총 대여 횟수가 5회 이상인 자동차 ID
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE TO_CHAR(START_DATE, 'YYYY-MM') BETWEEN '2022-08' AND '2022-10'
        GROUP BY CAR_ID HAVING COUNT(*) >= 5
     ) T
WHERE H.CAR_ID = T.CAR_ID
      AND TO_CHAR(START_DATE, 'YYYY-MM') BETWEEN '2022-08' AND '2022-10'
GROUP BY TO_NUMBER(TO_CHAR(H.START_DATE, 'MM')), H.CAR_ID
ORDER BY MONTH ASC, H.CAR_ID DESC