SELECT DISTINCT C.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR C, CAR_RENTAL_COMPANY_RENTAL_HISTORY H
WHERE C.CAR_ID = H.CAR_ID
      AND CAR_TYPE LIKE '%세단%'
      AND TO_CHAR(START_DATE, 'MM') LIKE '10'
ORDER BY CAR_ID DESC;